

apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
  labels:
    app: {{ .Values.appLabels.app | default "node-app" }}
    tier: {{ .Values.appLabels.tier }}
    version: {{ .Values.appLabels.version }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  selector:
    app: {{ .Values.appLabels.app }}

    
